apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  namespace: openshift-storage
  name: ocs-storagecluster
spec:
  manageNodes: false
  storageDeviceSets:
  - name: ocs-storagecluster
    count: 1
    replica: 3
    resources: {}
    placement: {}
    dataPVCTemplate:
      spec:
        storageClassName: gp3-csi
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 512Gi
    portable: true