# Variables meant to be overwritten
---
gitea_namespace: git
gitea_instance_name: repository
gitea_image_tag: latest
gitea_volumesize: 4Gi
gitea_pvolumesize: 4Gi
gitea_admin_user: gitea
gitea_admin_password: gitea
gitea_admin_email: opentlc-mgr@redhat.com
gitea_ssl: true
gitea_repos:
  - {"clone_addr":"https://github.com/cloud-native-robotz-hackathon/starter-app-python.git","repo_name":"starter-app-python"}
...
