---

- name: Create open-cluster-management Namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'open-cluster-management-namespace.yml' ) | from_yaml }}"
  tags:
    - acm

- name: Create ACM OperatorGroup
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'operator-group.yml' ) | from_yaml }}"
  tags:
    - acm

- name: Install ACM Operator Subscription
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'operator-subscription.yml' ) | from_yaml }}"
  tags:
    - acm

- name: "Get Installed CSV"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig }}"
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "advanced-cluster-management"
    namespace: "open-cluster-management"
  register: r_subscription
  retries: 30
  delay: 5
  until:
    - r_subscription.resources[0].status.currentCSV is defined
    - r_subscription.resources[0].status.currentCSV | length > 0
  tags: acm

- name: "Wait until CSV is installed"
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ r_subscription.resources[0].status.currentCSV }}"
    namespace: "open-cluster-management"
  register: r_csv
  retries: 30
  delay: 30
  until:
    - r_csv.resources[0].status.phase is defined
    - r_csv.resources[0].status.phase | length > 0
    - r_csv.resources[0].status.phase == "Succeeded"
  tags: acm



- name: Install MultiClusterHub Instance
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'multicluster-hub-instance.yml' ) | from_yaml }}"
  tags:
    - acm     