---
- name: Create ODS Namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'namespace.yml' ) | from_yaml }}"
  tags: ods

- name: Install RHODS Operator Subscription
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: rhods-operator
        namespace: redhat-ods-operator
      spec:
        channel: stable
        name: rhods-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        installPlanApproval: Automatic
  tags:
  - ods

- name: Wait for ODS CRD to be available
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: CustomResourceDefinition
    name: odhapplications.dashboard.opendatahub.io
  register: ods_crd
  retries: 10
  delay: 10
  until: ods_crd.resources | list | length == 1
  tags:
    - ods  

- name: Create RHODS Object Detection Projects
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'manifests/projects.yaml' ) | from_yaml_all }}"
  tags:
  - ods

- name: Create RHODS Object Detection Configuration
  command : "oc apply -k {{role_path}}/files/manifests"
  tags:
  - ods    




